import {fields,assess,sections,markdown,lines,example} from './engine.js';
const form=document.querySelector('#brief'),key='scopecheck:brief:v1';let data=Object.fromEntries(fields.map(f=>[f,''])),timer;
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>el.classList.remove('visible'),3000);}
try{const stored=JSON.parse(localStorage.getItem(key)||'null');if(stored&&typeof stored==='object')for(const f of fields)if(typeof stored[f]==='string')data[f]=stored[f].slice(0,4000);}catch{document.querySelector('#save-status').textContent='Device storage is unavailable';}
function fill(){for(const f of fields)form.elements[f].value=data[f];render();}
function element(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
function render(){const results=assess(data),score=results.filter(c=>c.done).length;document.querySelector('#count').textContent=`${score} / 8`;document.querySelector('#progress').style.width=`${score/8*100}%`;document.querySelector('#verdict').textContent=score===8?'Ready for a shared review.':score>=5?'Taking shape. Close the gaps.':'Let’s make the brief clearer.';const list=document.querySelector('#checks');list.replaceChildren();for(const check of results){const li=element('li',undefined,check.done?'done':'');const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',check.done?'M5 12l4 4 10-10':'M6 6h12v12H6z');svg.setAttribute('aria-hidden','true');svg.append(path);li.append(svg,element('span',check.label+(check.done?' — defined':' — missing')));list.append(li);}const questions=document.querySelector('#questions');questions.replaceChildren();const missing=results.filter(c=>!c.done);for(const text of missing.length?missing.map(c=>c.question):['Who approves the final work?','What is the payment schedule?','How will additional requests be quoted?'])questions.append(element('li',text));const preview=document.querySelector('#preview');preview.replaceChildren(element('h3',data.project.trim()||'Untitled project'),element('p','Prepared for '+(data.client.trim()||'client to be confirmed')),element('p','Draft for discussion','muted'));for(const [title,value] of sections(data)){preview.append(element('h4',title));if(title==='Deliverables'&&value.trim()){const ul=element('ul');for(const line of lines(value))ul.append(element('li',line));preview.append(ul);}else preview.append(element('p',value.trim()||'To be confirmed',value.trim()?'':'muted'));}}
function save(){try{localStorage.setItem(key,JSON.stringify(data));document.querySelector('#save-status').textContent='Saved on this device';}catch{document.querySelector('#save-status').textContent='Not saved — download your scope';}}
form.addEventListener('input',()=>{for(const f of fields)data[f]=form.elements[f].value;render();save();});form.addEventListener('submit',e=>e.preventDefault());
document.querySelector('#example').addEventListener('click',()=>{if(fields.some(f=>data[f].trim())){toast('Clear the current brief before loading an example.');return;}data={...example};fill();save();});
document.querySelector('#reset').addEventListener('click',()=>document.querySelector('#reset-confirm').hidden=false);document.querySelector('#cancel-reset').addEventListener('click',()=>document.querySelector('#reset-confirm').hidden=true);document.querySelector('#confirm-reset').addEventListener('click',()=>{data=Object.fromEntries(fields.map(f=>[f,'']));fill();save();document.querySelector('#reset-confirm').hidden=true;toast('Brief cleared');});
document.querySelector('#copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(markdown(data));toast('Scope copied');}catch{toast('Copy unavailable here. Download the scope instead.');}});
document.querySelector('#download').addEventListener('click',()=>{const blob=new Blob([markdown(data)],{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(data.project.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70)||'project')+'-scope.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Scope downloaded');});document.querySelector('#print').addEventListener('click',()=>window.print());fill();
